name: Update and Deploy Site

on:
  schedule:
    - cron: "*/5 * * * *"  # каждые 5 минут
  workflow_dispatch:       # возможность запускать вручную

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Устанавливаем зависимости
      - name: Install deps
        run: pip install requests beautifulsoup4

      # 4. Запускаем твой скрипт
      - name: Run script
        run: python places.py

      # 5. Коммитим изменения, если есть
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "update index.html [skip ci]" || echo "No changes"

      # 6. Деплоим на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # корень репозитория
